---
# author: lework

- name: verify | 查看验证url状态。
  uri: 
    url: "{{ deploy_verify_url }}"
    headers: "{{ deploy_verify_url_headers | d('') }}"
    status_code: "{{ deploy_verify_url_status_code | d('200')}}"
  register: curl_result
  until: curl_result.status == deploy_verify_url_status_code
  retries: 5
  delay: 3
  changed_when: false
  check_mode: no
  become: no
  when: deploy_verify_uri is defined and deploy_verify_uri != ""
