---
# author: lework

- block:
  - name: install | Check if alertmanager local file is already configured.
    stat: path={{ software_files_path }}/{{ alertmanager_binary_file }}
    register: reg_alertmanager_file_result
  
  - name: install | Make sure the software directory exists.
    file: path={{ software_files_path }} state=directory
    when: not reg_alertmanager_file_result.stat.exists
  
  - name: install | Download alertmanager file.
    get_url: url={{ alertmanager_binary_file_url }} dest={{ software_files_path }} validate_certs=no
    when: not reg_alertmanager_file_result.stat.exists
  connection: local
  run_once: yes

- name: install | Create alertmanager system group.
  group:
    name: "{{ alertmanager_group }}"
    system: true
    state: present

- name: install | Create alertmanager system user.
  user:
    name: "{{ alertmanager_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ alertmanager_group }}"
    createhome: false
    home: "{{ alertmanager_db_path }}"
    
- name: install | Confirm the existence of the installation directory.
  file: path={{ software_install_path }} state=directory

- name: install | Copy alertmanager file to agent.
  unarchive:
    src: "{{ software_files_path }}/{{ alertmanager_binary_file }}"
    dest: "{{ software_install_path }}"
    creates: "{{ software_install_path }}/{{ alertmanager_binary_file | regex_replace('\\.tar\\.gz$', '') }}/alertmanager"
    owner: "root"
    group: "{{ alertmanager_group }}"
    
- name: install | Create alertmanager binary path soft link.
  file:
    src: "{{ software_install_path }}/{{ alertmanager_binary_file | regex_replace('\\.tar\\.gz$', '') }}"
    dest: "{{ software_install_path }}/alertmanager"
    state: link
    owner: "root"
    group: "{{ alertmanager_group }}"

- name: install | Create systemd service unit.
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart alertmanager