---
# author: lework

software_files_path: "/opt/software"
software_install_path: "/usr/local"

alertmanager_version: "0.21.0"
alertmanager_binary_file: alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz
alertmanager_binary_file_url: https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/{{ alertmanager_binary_file }}

alertmanager_user: alertmanager
alertmanager_group: alertmanager

alertmanager_service_status: started
alertmanager_service_enabled: yes

alertmanager_conf_path: /etc/alertmanager
alertmanager_templates_path: "{{ alertmanager_conf_path }}/templates"
alertmanager_db_path: /var/lib/alertmanager

alertmanager_port: "9093"
alertmanager_web_listen_address: "0.0.0.0:{{ alertmanager_port }}"
alertmanager_web_external_url: ''

alertmanager_config_flags_extra:
  log.level: info

alertmanager_cluster: {}
# alertmanager_cluster:
#    listen-address: "{{ ansible_default_ipv4.address }}:6783"
#    peers:
#      - "{{ ansible_default_ipv4.address }}:6783"


alertmanager_conf:
  global:
    resolve_timeout: 5m
  route:
    group_by: ['alertname']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 1h
    receiver: 'web.hook'
  receivers:
  - name: 'web.hook'
    webhook_configs:
    - url: 'http://127.0.0.1:5001/'
  inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'dev', 'instance']

alertmanager_conf_file: ""
alertmanager_template_files: []
