---
# author: lework

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: 1.install.yml
- include_tasks: 2.configure.yml 
- include_tasks: 3.logrotate.yml
- include_tasks: 4.service.yml
- include_tasks: 5.cluster.yml
  when: redis_cluster
