---
- name: 目录病毒巡检
  hosts: server
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root
  vars:
   check_report_path: /tmp
   check_mail_host: "smtp.qq.com"
   check_mail_port: "25"
   check_mail_username: "2727250655@qq.com"
   check_mail_password: "xykvqvunpm----"
   check_mail_to: ["dt@dyclub.org"]
   check_playbook_name: "playbook-virus-check.yml"
  roles:
   - virus-check